import type { Metadata } from "next";
import Sidenav from "./components/Sidenav";
import Topnav from "../(demo)/components/Topnav";

export const metadata: Metadata = {
  title: "Temari",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen overflow-hidden bg-gray-50">
      <Sidenav />
      <main className="flex-1 overflow-auto rounded-l-4xl bg-white">
        <div className="min-h-screen">
          <div className="sticky top-0 z-50 bg-white">
            <Topnav />
          </div>
          {children}
        </div>
      </main>
    </div>
  );
}
